package de.marcely.pocketcraft.utils.shared;

public enum InventorySlotGroup {
	
	PLAYER_HOTBAR,
	PLAYER_CONTENT,
	PLAYER_ARMOR,
	PLAYER_SHIELD,
	PLAYER_CRAFTING_INPUT,
	PLAYER_CRAFTING_OUTPUT,
	
	CHEST,
	
	CRAFTING_TABLE_INPUT,
	CRAFTING_TABLE_OUTPUT,
	
	FURNACE_INPUT,
	FURNACE_FUEl,
	FURNACE_OUTPUT,
	
	DISPENSER,
	
	ENCHANTMENT_TABLE_ITEM,
	ENCHANTMENT_TABLE_LAPIS,
	
	BREWING_STAND_BOTTLES,
	BREWING_STAND_INGREDIENT,
	BREWING_STAND_BLAZE_POWDER,
	
	VILLAGER_INPUT_1,
	VILLAGER_INPUT_2,
	VILLAGER_OUTPUT,
	
	BEACON,
	
	ANVIL_INPUT_1,
	ANVIL_INPUT_2,
	ANVIL_OUTPUT,
	
	HOPPER,
	
	HORSE_SADDLE,
	HORSE_ARMOR;
}
